name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install/Update
      run: |
        sudo apt-get update
        sudo apt-get -y install zip
        # This does not work currently (403 error, may be intentionally blocked)
        sudo dkp-pacman -Syu || true

    - name: Build GCMM
      run: |
        make clean all

    - name: Prepare release archive
      run: |
        mkdir release
        cp readme.txt release
        mkdir -p release/wii
        cp hbc/* release/wii
        cp gcmm_WII.dol release/wii/boot.dol
        mkdir -p release/gamecube
        cp gcmm_GC.dol release/gamecube/gcmm.dol

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Compress folder
      run: |
        zip -r gcmm.zip release/*

    - uses: actions/upload-artifact@v2
      with:
        name: gcmm-${{steps.slug.outputs.sha8}}
        path: release/*

    - name: Extract tag name
      if: startsWith(github.ref, 'refs/tags/')
      id: tag
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Rename release for tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mv gcmm.zip gcmm-${{steps.tag.outputs.VERSION}}.zip

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: gcmm*.zip
        tag_name: ${{steps.tag.outputs.VERSION}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
